version: '3'
services:
  lpostgres:
    image: postgres:14.13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library
    ports:
      -  '5434:5432'