version: "3"

services:
  lpostgres:
    image: postgres:14.13
    env_file: configs/local.env
    ports:
      -  '5434:5432'
  rabbitmq:
    image: rabbitmq:management
    env_file: configs/local.env
    ports:
      - "5672:5672"
      - "15672:15672"
      